#!/usr/bin/env bash
#
# Refuses to modify a migration that has already been committed.
#
# This is the one migration mistake with no local symptom. Prisma records a
# checksum of every applied migration; editing the SQL afterwards makes
# `migrate deploy` fail with "migration modified after being applied" on every
# other machine and in every future deployment, while the machine that made the
# edit stays perfectly happy. Reviewing the diff does not help either — the
# change looks like an ordinary SQL edit.
#
# A migration is history. To change the schema, add a migration.
#
# Escape hatch: a migration that is not yet committed to git is still a draft,
# and editing it is fine. That is what makes iterating on a new migration
# possible without disabling the hook.
set -uo pipefail

payload=$(cat)

command -v jq >/dev/null 2>&1 || exit 0
file=$(printf '%s' "$payload" | jq -r '.tool_input.file_path // empty')

[ -n "$file" ] || exit 0
case "$file" in
  */prisma/migrations/*) ;;
  *) exit 0 ;;
esac

# migration_lock.toml says so itself: "Please do not edit this file manually".
case "$file" in
  */migration_lock.toml)
    echo "migration_lock.toml is managed by Prisma and must not be edited." >&2
    exit 2
    ;;
esac

repo_root="${CLAUDE_PROJECT_DIR:-.}"
cd "$repo_root" 2>/dev/null || exit 0

# Untracked means "not yet history" — a draft migration being iterated on.
if ! git ls-files --error-unmatch "$file" >/dev/null 2>&1; then
  exit 0
fi

{
  echo "Refusing to edit a committed migration:"
  echo "    $file"
  echo
  echo "Prisma checksums every applied migration. Editing this file makes"
  echo "\`prisma migrate deploy\` fail on every other machine with \"migration"
  echo "modified after being applied\" — while this one keeps working, so the"
  echo "damage is invisible from here."
  echo
  echo "A migration is history. Change the schema in prisma/schema/ and add a NEW"
  echo "migration; see CLAUDE.md section 9 for the non-interactive recipe."
  echo
  echo "If this migration has genuinely never been applied anywhere — including"
  echo "any teammate's database — say so explicitly and the user can decide."
} >&2
exit 2
